import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import path from "path";

const dbPath = path.join(process.cwd(), "dev.db");
const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("Seeding database...");

  // ==================== COMPANIES ====================
  const companies = await Promise.all([
    // Hong Kong Companies
    prisma.company.create({
      data: {
        name: "prudential-hk",
        slug: "prudential-hk",
        displayName: "Prudential Hong Kong",
        region: "Hong Kong",
        country: "Hong Kong",
        website: "https://www.prudential.com.hk",
        logoUrl: "/logos/prudential.png",
        foundedYear: 1964,
        headquarters: "Hong Kong",
        description: "Prudential Hong Kong is a leading life insurance company that has been serving customers in Hong Kong for over 60 years, offering a comprehensive range of protection, savings, and investment-linked products.",
        regulator: "Insurance Authority (IA)",
        amBestRating: "A+",
        moodysRating: "A2",
        spRating: "A+",
      },
    }),
    prisma.company.create({
      data: {
        name: "aia-hk",
        slug: "aia-hk",
        displayName: "AIA Hong Kong",
        region: "Hong Kong",
        country: "Hong Kong",
        website: "https://www.aia.com.hk",
        logoUrl: "/logos/aia.png",
        foundedYear: 1919,
        headquarters: "Hong Kong",
        description: "AIA is the largest independent publicly listed pan-Asian life insurance group, serving over 700,000 customers in Hong Kong and Macau. With a history spanning over a century since 1919, AIA is ranked No.1 in Hong Kong's insurance market and leads globally in MDRT membership.",
        regulator: "Insurance Authority (IA)",
        amBestRating: "A+",
        moodysRating: "A2",
        spRating: "AA-",
      },
    }),
    prisma.company.create({
      data: {
        name: "manulife-hk",
        slug: "manulife-hk",
        displayName: "Manulife Hong Kong",
        region: "Hong Kong",
        country: "Hong Kong",
        website: "https://www.manulife.com.hk",
        logoUrl: "/logos/manulife.png",
        foundedYear: 1897,
        headquarters: "Hong Kong",
        description: "Manulife Hong Kong, part of the global Manulife Financial Corporation founded in 1897, provides financial protection and wealth management solutions to individuals and businesses in Hong Kong, with a strong focus on retirement and investment products.",
        regulator: "Insurance Authority (IA)",
        amBestRating: "A+",
        moodysRating: "A1",
        spRating: "AA-",
      },
    }),
    prisma.company.create({
      data: {
        name: "axa-hk",
        slug: "axa-hk",
        displayName: "AXA Hong Kong",
        region: "Hong Kong",
        country: "Hong Kong",
        website: "https://www.axa.com.hk",
        logoUrl: "/logos/axa.png",
        foundedYear: 1986,
        headquarters: "Hong Kong",
        description: "AXA Hong Kong offers a comprehensive range of life, health, savings, and general insurance products. With the Emma by AXA digital platform, AXA provides innovative self-servicing solutions and a holistic wellness programme called BetterMe.",
        regulator: "Insurance Authority (IA)",
        amBestRating: "A+",
        moodysRating: "A1",
        spRating: "A+",
      },
    }),
    prisma.company.create({
      data: {
        name: "fwd-hk",
        slug: "fwd-hk",
        displayName: "FWD Hong Kong",
        region: "Hong Kong",
        country: "Hong Kong",
        website: "https://www.fwd.com.hk",
        logoUrl: "/logos/fwd.png",
        foundedYear: 2013,
        headquarters: "Hong Kong",
        description: "FWD is a pan-Asian life insurance business headquartered in Hong Kong, offering life insurance, medical and critical illness protection, savings plans, retirement solutions, and investment-linked insurance with a focus on digital-first customer experience.",
        regulator: "Insurance Authority (IA)",
        moodysRating: "A3",
      },
    }),
    // Mainland China Companies
    prisma.company.create({
      data: {
        name: "ping-an",
        slug: "ping-an",
        displayName: "Ping An Insurance",
        region: "Mainland China",
        country: "China",
        website: "https://www.pingan.com",
        logoUrl: "/logos/pingan.png",
        foundedYear: 1988,
        headquarters: "Shenzhen, China",
        description: "Ping An Insurance (Group) Company of China is one of the world's largest financial services companies, offering insurance, banking, securities, and investment services. Ping An's healthcare ecosystem covers 100% of China's top 100 hospitals and tertiary hospitals.",
        regulator: "National Financial Regulatory Administration (NFRA)",
        spRating: "A",
        fitchRating: "A",
      },
    }),
    prisma.company.create({
      data: {
        name: "china-life",
        slug: "china-life",
        displayName: "China Life Insurance",
        region: "Mainland China",
        country: "China",
        website: "https://www.chinalife.com.cn",
        logoUrl: "/logos/chinalife.png",
        foundedYear: 1949,
        headquarters: "Beijing, China",
        description: "China Life Insurance (Group) Company is the largest life insurance company in China and a Fortune Global 500 company, offering life insurance, overseas business, asset management, health investment, and property insurance across its extensive nationwide network.",
        regulator: "National Financial Regulatory Administration (NFRA)",
        spRating: "A",
        fitchRating: "A+",
      },
    }),
    prisma.company.create({
      data: {
        name: "taikang-life",
        slug: "taikang-life",
        displayName: "Taikang Insurance Group",
        region: "Mainland China",
        country: "China",
        website: "https://www.taikang.com",
        logoUrl: "/logos/taikang.png",
        foundedYear: 1996,
        headquarters: "Beijing, China",
        description: "Taikang Insurance Group operates across three core businesses: insurance, asset management, and healthcare (medical & elderly care). Managing over ¥359.5 billion in pension assets and ¥774.2 billion in third-party assets, Taikang has opened 30 Taikang Home elderly care communities nationwide.",
        regulator: "National Financial Regulatory Administration (NFRA)",
      },
    }),
    prisma.company.create({
      data: {
        name: "cpic-life",
        slug: "cpic-life",
        displayName: "China Pacific Insurance (CPIC)",
        region: "Mainland China",
        country: "China",
        website: "https://www.cpic.com.cn",
        logoUrl: "/logos/cpic.png",
        foundedYear: 1991,
        headquarters: "Shanghai, China",
        description: "China Pacific Insurance (Group) Co., Ltd. is one of China's largest insurance groups, offering property insurance, life insurance, asset management, health insurance, and pension services through its subsidiaries. CPIC serves customers nationwide with its 24/7 hotline 95500.",
        regulator: "National Financial Regulatory Administration (NFRA)",
        spRating: "A",
      },
    }),
    prisma.company.create({
      data: {
        name: "new-china-life",
        slug: "new-china-life",
        displayName: "New China Life Insurance",
        region: "Mainland China",
        country: "China",
        website: "https://www.newchinalife.com",
        logoUrl: "/logos/newchinalife.png",
        foundedYear: 1996,
        headquarters: "Beijing, China",
        description: "New China Life Insurance Co., Ltd. (NCI) is a leading life insurance company in China listed on the Shanghai, Hong Kong, and New York stock exchanges. NCI extends into elderly care, health management, and asset management, operating 19 health checkup centres and a rehabilitation hospital in Beijing.",
        regulator: "National Financial Regulatory Administration (NFRA)",
        fitchRating: "A",
      },
    }),
  ]);

  console.log(`Created ${companies.length} companies`);

  // ==================== PRODUCTS ====================
  const products = [];

  // Hong Kong Products
  const hkProducts = [
    // Prudential - 6 products
    {
      companyId: companies[0].id,
      name: "Prudential Critical Illness Plan",
      slug: "prudential-ci-plan",
      displayName: "Prudential Critical Illness Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "multiple-claims", "cancer-coverage"],
      summary: "A comprehensive critical illness plan offering coverage for multiple conditions with flexible premium terms.",
      brochureUrl: "/pdfs/prulife-protector-ii-en.pdf",
    },
    {
      companyId: companies[0].id,
      name: "Prudential Enlight Savings",
      slug: "prudential-enlit-savings",
      displayName: "Prudential Enlight Savings",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "education", "guaranteed", "endowment"],
      summary: "A savings insurance series with guaranteed financial support for children's education and lifelong protection.",
      brochureUrl: "/pdfs/enlit-product-brochure-en.pdf",
    },
    {
      companyId: companies[0].id,
      name: "Evergreen Growth Saver Plus II",
      slug: "prudential-evergreen-growth",
      displayName: "Evergreen Growth Saver Plus II",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "retirement", "long-term", "wealth-transfer"],
      summary: "Long-term savings for retirement, education or passing down wealth through the generations.",
      brochureUrl: "/pdfs/evergreen-growth-saver-plus-ii-en.pdf",
    },
    {
      companyId: companies[0].id,
      name: "Prime Ace Insurance Plan",
      slug: "prudential-prime-ace",
      displayName: "Prime Ace Insurance Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["USD"],
      tags: ["savings", "legacy", "wealth-transfer", "premium"],
      summary: "The accelerated path to get ahead, build your wealth, and craft a legacy with just 3 years of premiums.",
      brochureUrl: "/pdfs/pace-product-brochure-en.pdf",
    },
    {
      companyId: companies[0].id,
      name: "Prime Eternity",
      slug: "prudential-prime-eternity",
      displayName: "Prime Eternity",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "single-premium", "legacy", "wealth-transfer"],
      summary: "Crafting Prime Eternity wealth begins with a single premium: seamlessly grow, access and pass on your wealth for generations.",
      brochureUrl: "/pdfs/prime-eternity-en.pdf",
    },
    // Prudential Guardian CI Series
    {
      companyId: companies[0].id,
      name: "Prudential Guardian Critical Illness Plan Series",
      slug: "pru-guardian-ci-series",
      displayName: "Prudential Guardian CI Plan Series",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "guardian", "comprehensive", "participating"],
      summary: "Participating critical illness plan series offering comprehensive protection for the whole family.",
      brochureUrl: "/pdfs/pru-guardian-ci-series.pdf",
    },
    // Prudential CI Extended Care III
    {
      companyId: companies[0].id,
      name: "Prudential Critical Illness Extended Care III",
      slug: "pru-ci-extended-care-iii",
      displayName: "Prudential CI Extended Care III",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "extended-care", "comprehensive", "multiple-claims"],
      summary: "Extended critical illness care with multiple claims and comprehensive condition coverage.",
      brochureUrl: "/pdfs/pru-ci-extended-care-iii.pdf",
    },
    // Prudential Entrust Multi-Currency Plan
    {
      companyId: companies[0].id,
      name: "Prudential Entrust Multi-Currency Plan",
      slug: "pru-entrust-multi-currency",
      displayName: "Prudential Entrust Multi-Currency Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD", "CNY", "GBP", "EUR", "CAD", "AUD"],
      tags: ["savings", "multi-currency", "wealth-transfer", "legacy"],
      summary: "Multi-currency savings plan for diversified wealth management and intergenerational transfer.",
      brochureUrl: "/pdfs/pru-entrust-multi-currency.pdf",
    },
    // AIA - 2 products
    {
      companyId: companies[1].id,
      name: "AIA Critical Illness Elite",
      slug: "aia-ci-elite",
      displayName: "AIA Critical Illness Elite",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "elite", "cancer-multiple-claims"],
      summary: "Premium critical illness coverage with extensive condition definitions and multiple claim benefits.",
      brochureUrl: "/pdfs/aia-assemble-ci.pdf",
    },
    {
      companyId: companies[1].id,
      name: "AIA Savings Leader",
      slug: "aia-savings-leader",
      displayName: "AIA Savings Leader",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "participating", "education", "retirement"],
      summary: "A leading savings product with guaranteed and non-guaranteed benefits for education and retirement planning.",
      brochureUrl: "/pdfs/aia-savings-leader.pdf",
    },
    // AIA additional CI products
    {
      companyId: companies[1].id,
      name: "AIA Cancer Care Essence",
      slug: "aia-cancer-care",
      displayName: "AIA Cancer Care Essence",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "cancer", "affordable"],
      summary: "Affordable cancer and life protection plan providing targeted support during critical moments.",
      brochureUrl: "/pdfs/aia-cancer-care.pdf",
    },
    {
      companyId: companies[1].id,
      name: "AIA Executive Care Pro 2",
      slug: "aia-executive-care-pro-2",
      displayName: "AIA Executive Care Pro 2",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "premium", "comprehensive"],
      summary: "Premium critical illness plan with comprehensive coverage and enhanced benefits.",
      brochureUrl: "/pdfs/aia-executive-care-pro-2.pdf",
    },
    {
      companyId: companies[1].id,
      name: "AIA Essence On Your Side",
      slug: "aia-essence-on-your-side",
      displayName: "AIA Essence On Your Side",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "participating", "58-conditions"],
      summary: "Participating CI plan covering 58 critical illnesses with cancer, heart disease and stroke extras.",
      brochureUrl: "/pdfs/aia-essence-on-your-side.pdf",
    },
    // AIA On Your Side 2
    {
      companyId: companies[1].id,
      name: "AIA On Your Side Insurance Plan 2",
      slug: "aia-on-your-side-2",
      displayName: "AIA On Your Side Insurance Plan 2",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "participating", "comprehensive"],
      summary: "Participating critical illness plan providing comprehensive protection with loyalty benefits.",
      brochureUrl: "/pdfs/aia-on-your-side-2.pdf",
    },
    // AIA Cancer Guardian 3
    {
      companyId: companies[1].id,
      name: "AIA Cancer Guardian 3",
      slug: "aia-cancer-guardian-3",
      displayName: "AIA Cancer Guardian 3",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "cancer", "guardian", "comprehensive"],
      summary: "Comprehensive cancer protection plan with multiple claim benefits and recovery support.",
      brochureUrl: "/pdfs/aia-cancer-guardian-3.pdf",
    },
    // AIA GlobalFlexi Savings
    {
      companyId: companies[1].id,
      name: "AIA GlobalFlexi Savings Insurance Plan",
      slug: "aia-globalflexi-savings",
      displayName: "AIA GlobalFlexi Savings Insurance Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD", "CNY", "GBP", "EUR"],
      tags: ["savings", "global", "flexible", "multi-currency"],
      summary: "Global flexible savings plan with multi-currency options for international wealth management.",
      brochureUrl: "/pdfs/aia-globalflexi-savings.pdf",
    },
    // AIA Wealth Flexi Savings
    {
      companyId: companies[1].id,
      name: "AIA Wealth Flexi Savings Insurance Plan",
      slug: "aia-wealth-flexi-savings",
      displayName: "AIA Wealth Flexi Savings Insurance Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "wealth", "flexible", "premium"],
      summary: "Premium wealth savings plan with flexible withdrawal options and competitive returns.",
      brochureUrl: "/pdfs/aia-wealth-flexi-savings.pdf",
    },
    // Manulife Genesis Centurion (世纪传承保障计划)
    {
      companyId: companies[2].id,
      name: "Manulife Genesis Centurion",
      slug: "manulife-genesis-centurion",
      displayName: "Manulife Genesis Centurion",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "legacy", "wealth-transfer", "premium"],
      summary: "Premium savings plan for wealth accumulation and intergenerational legacy planning.",
      brochureUrl: "/pdfs/genesis-centurion.pdf",
    },
    // Manulife IncomeGuard CI (宏健守护危疾入息保障)
    {
      companyId: companies[2].id,
      name: "Manulife IncomeGuard Critical Illness Protector",
      slug: "manulife-incomeguard-ci",
      displayName: "Manulife IncomeGuard CI",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "income", "comprehensive", "multiple-claims"],
      summary: "Critical illness protection with regular income benefit during recovery period.",
      brochureUrl: "/pdfs/incomeguard-critical-illness-protector.pdf",
    },
    // Manulife IncomeShield CI
    {
      companyId: companies[2].id,
      name: "Manulife IncomeShield Critical Illness Protector",
      slug: "manulife-incomeshield-ci",
      displayName: "Manulife IncomeShield CI",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "income", "shield", "comprehensive"],
      summary: "Comprehensive critical illness shield with income protection benefits.",
      brochureUrl: "/pdfs/incomeshield-critical-illness-protector.pdf",
    },
    // Manulife Bright Care Pro (活耀人生危疾保)
    {
      companyId: companies[2].id,
      name: "Manulife Bright Care Pro",
      slug: "manulife-bright-care-pro",
      displayName: "Manulife Bright Care Pro",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "bright-care", "comprehensive", "pro"],
      summary: "Professional-grade critical illness protection with comprehensive coverage and wellness benefits.",
      brochureUrl: "/pdfs/manulife-bright-care-pro.pdf",
    },
    // Manulife Prestige Achiever
    {
      companyId: companies[2].id,
      name: "Manulife Prestige Achiever",
      slug: "manulife-prestige-achiever",
      displayName: "Manulife Prestige Achiever",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "prestige", "achiever", "wealth"],
      summary: "Prestigious savings plan for wealth achievement and long-term financial goals.",
      brochureUrl: "/pdfs/prestige-achiever.pdf",
    },
    {
      companyId: companies[4].id,
      name: "FWD Noble Fortune",
      slug: "fwd-noble-fortune",
      displayName: "FWD Noble Fortune",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "universal-life", "wealth-transfer"],
      summary: "A universal life product with savings element for wealth accumulation and legacy planning.",
      brochureUrl: "/pdfs/fwd-noble-fortune.pdf",
    },
    // FWD Crisis One Master (危疾緻尚保)
    {
      companyId: companies[4].id,
      name: "FWD Crisis One Master",
      slug: "fwd-crisis-one-master",
      displayName: "FWD Crisis One Master",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "multiple-claims", "cancer", "comprehensive"],
      summary: "Comprehensive critical illness protection covering 68 major conditions and 80 severe diseases with up to 2080% of sum insured.",
      brochureUrl: "/pdfs/fwd-crisis-one-master.pdf",
    },
    // FWD Crisis U Supporter (危疾應援保)
    {
      companyId: companies[4].id,
      name: "FWD Crisis U Supporter",
      slug: "fwd-crisis-u-supporter",
      displayName: "FWD Crisis U Supporter",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "innovative", "cancer", "mental-health"],
      summary: "Innovative critical illness plan with 10Life 5-star rating, covering cancer, heart disease, stroke and mental health support.",
      brochureUrl: "/pdfs/fwd-crisis-u-supporter.pdf",
    },
    // FWD EasyCover (好易揀危疾保障)
    {
      companyId: companies[4].id,
      name: "FWD EasyCover Critical Illness Plan",
      slug: "fwd-easycover-ci",
      displayName: "FWD EasyCover Critical Illness Plan",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "CRITICAL_ILLNESS" as const,
      currency: "HKD",
      tags: ["critical-illness", "affordable", "basic", "cancer"],
      summary: "Affordable critical illness coverage including cancer, acute myocardial infarction and stroke, extended to unknown diseases.",
      brochureUrl: "/pdfs/fwd-easycover-ci.pdf",
    },
    // FWD MaxFocus Legacy II (盈聚天下II)
    {
      companyId: companies[4].id,
      name: "FWD MaxFocus Legacy II Insurance Plan",
      slug: "fwd-maxfocus-legacy-ii",
      displayName: "FWD MaxFocus Legacy II",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "legacy", "participating", "wealth-transfer"],
      summary: "Participating savings plan for wealth accumulation and legacy planning with flexible premium options.",
      brochureUrl: "/pdfs/fwd-maxfocus-legacy-ii.pdf",
    },
    // FWD WealthICON Supreme III (智盈汇聚优越版III)
    {
      companyId: companies[4].id,
      name: "FWD WealthICON Supreme III",
      slug: "fwd-wealthicon-supreme-iii",
      displayName: "FWD WealthICON Supreme III",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "participating", "wealth", "premium"],
      summary: "Premium participating savings plan with comprehensive wealth management features and competitive returns.",
      brochureUrl: "/pdfs/fwd-wealthicon-supreme-iii.pdf",
    },
    // FWD WealthICON Horizon (智盈超凡)
    {
      companyId: companies[4].id,
      name: "FWD WealthICON Horizon",
      slug: "fwd-wealthicon-horizon",
      displayName: "FWD WealthICON Horizon",
      region: "Hong Kong",
      country: "Hong Kong",
      category: "SAVINGS" as const,
      currency: "HKD",
      supportedCurrencies: ["HKD", "USD"],
      tags: ["savings", "horizon", "wealth", "long-term"],
      summary: "Long-term wealth accumulation plan with horizon benefits and flexible premium options.",
      brochureUrl: "/pdfs/fwd-wealthicon-horizon.pdf",
    },
  ];

  // Mainland Products
  const mainlandProducts = [
    // Ping An
    {
      companyId: companies[5].id,
      name: "Ping An Shengshi Jinyue Premium",
      slug: "ping-an-shengshi-jinyue-premium",
      displayName: "Ping An Shengshi Jinyue (Premium Edition)",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "increasing-sum", "whole-life", "premium", "guaranteed"],
      summary: "Premium edition increasing sum insured whole life product with guaranteed cash value growth.",
      brochureUrl: "/pdfs/pingan-shengshi-jinyue-zunxiang.pdf",
    },
    {
      companyId: companies[5].id,
      name: "Ping An Ruyi Quanneng Critical Illness 2025",
      slug: "pingan-ruyi-quanneng-ci",
      displayName: "Ping An Ruyi Quanneng CI 2025",
      region: "Mainland China",
      country: "China",
      category: "CRITICAL_ILLNESS" as const,
      currency: "CNY",
      tags: ["critical-illness", "mainland", "rider", "comprehensive"],
      summary: "Critical illness rider providing advance payment for major diseases, part of Ruyi Quanneng series.",
      brochureUrl: "/pdfs/pingan-ruyi-quanneng-2025-ci.pdf",
    },
    {
      companyId: companies[5].id,
      name: "Ping An Ruyi Quanneng Endowment 2025",
      slug: "pingan-ruyi-quanneng-main",
      displayName: "Ping An Ruyi Quanneng 2025",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "mainland", "endowment", "maturity-benefit"],
      summary: "Endowment insurance plan providing maturity survival benefit and death benefit, paired with CI rider for comprehensive protection.",
      brochureUrl: "/pdfs/pingan-ruyi-quanneng-2025-main.pdf",
    },
    // Taikang
    {
      companyId: companies[7].id,
      name: "Taikang Zengduoduo",
      slug: "taikang-zengduoduo",
      displayName: "Taikang Zengduoduo (增多多)",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "increasing-sum", "popular", "guaranteed"],
      summary: "A popular increasing sum insured product known for competitive guaranteed returns.",
      brochureUrl: "/pdfs/taikang-fangxin-caifu.pdf",
    },
    {
      companyId: companies[7].id,
      name: "Taikang Zunxiang Shijia (Increasing Edition)",
      slug: "taikang-zunxiang-shijia-zeng-e",
      displayName: "Taikang Zunxiang Shijia (Increasing Edition)",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "increasing-sum", "whole-life", "premium"],
      summary: "Premium increasing sum insured whole life product from Taikang for long-term wealth accumulation.",
      brochureUrl: "/pdfs/taikang-zunxiang-shijia-zeng-e.pdf",
    },
    {
      companyId: companies[7].id,
      name: "Taikang Zunxiang Shijia (Flagship Edition)",
      slug: "taikang-zunxiang-shijia-flagship",
      displayName: "Taikang Zunxiang Shijia (Flagship Edition)",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "whole-life", "flagship", "premium"],
      summary: "Flagship whole life product from Taikang with comprehensive wealth management features.",
      brochureUrl: "/pdfs/taikang-zunxiang-shijia-flagship.pdf",
    },
    {
      companyId: companies[7].id,
      name: "Taikang Lexiang Jiankang 2026",
      slug: "taikang-lexiangjiankang-2026",
      displayName: "Taikang Lexiang Jiankang 2026",
      region: "Mainland China",
      country: "China",
      category: "CRITICAL_ILLNESS" as const,
      currency: "CNY",
      tags: ["critical-illness", "mainland", "comprehensive", "2026"],
      summary: "Comprehensive critical illness insurance covering major and minor conditions with 2026 updates.",
      brochureUrl: "/pdfs/taikang-lexiangjiankang-2026.pdf",
    },
    // CPIC
    {
      companyId: companies[8].id,
      name: "CPIC Evergreen Whole Life",
      slug: "cpic-evergreen-whole-life",
      displayName: "CPIC Evergreen Whole Life (增额终身寿)",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "increasing-sum", "whole-life", "evergreen"],
      summary: "A whole life savings product with steady cash value growth and flexible withdrawal options.",
      brochureUrl: "/pdfs/cpic-xin-xiang-ban.pdf",
    },
    {
      companyId: companies[8].id,
      name: "CPIC Xiangban Zhizun 2024S",
      slug: "cpic-xiangbanzhizun-2024s",
      displayName: "CPIC Xiangban Zhizun 2024S",
      region: "Mainland China",
      country: "China",
      category: "SAVINGS" as const,
      currency: "CNY",
      tags: ["savings", "participating", "whole-life", "premium"],
      summary: "Participating whole life savings plan with premium benefits and dividend distribution.",
      brochureUrl: "/pdfs/cpic-xiangbanzhizun-2024s.pdf",
    },
    {
      companyId: companies[8].id,
      name: "CPIC Jinsheng Wuyou Kids",
      slug: "cpic-jinshengwuyou-kids",
      displayName: "CPIC Jinsheng Wuyou (Kids Edition)",
      region: "Mainland China",
      country: "China",
      category: "CRITICAL_ILLNESS" as const,
      currency: "CNY",
      tags: ["critical-illness", "mainland", "kids", "comprehensive"],
      summary: "Children's critical illness insurance covering major and minor conditions with juvenile-specific protections.",
      brochureUrl: "/pdfs/cpic-jinshengwuyou-kids.pdf",
    },
    {
      companyId: companies[8].id,
      name: "CPIC Wenying Jinsheng Critical Illness",
      slug: "cpic-wenyingjinsheng-ci",
      displayName: "CPIC Wenying Jinsheng CI",
      region: "Mainland China",
      country: "China",
      category: "CRITICAL_ILLNESS" as const,
      currency: "CNY",
      tags: ["critical-illness", "mainland", "rider", "stable"],
      summary: "Stable critical illness rider providing comprehensive coverage for major diseases.",
      brochureUrl: "/pdfs/cpic-wenyingjinsheng-ci.pdf",
    },
  ];

  const allProducts = [...hkProducts, ...mainlandProducts];

  for (const productData of allProducts) {
    const product = await prisma.product.create({
      data: {
        ...productData,
        tags: JSON.stringify(productData.tags),
        supportedCurrencies: (productData as Record<string, unknown>).supportedCurrencies
          ? JSON.stringify((productData as Record<string, unknown>).supportedCurrencies)
          : "[]",
        productStatus: "active",
      },
    });
    products.push(product);
  }

  console.log(`Created ${products.length} products`);

  // ==================== PRODUCT DETAILS ====================
  const ciProducts = products.filter((p) => p.category === "CRITICAL_ILLNESS");
  const savingsProducts = products.filter((p) => p.category === "SAVINGS");

  for (const product of ciProducts) {
    // Product-specific CI details from official brochures
    const ciDetails: Record<string, any> = {
      // Prudential PRULife Protector II - from PDF
      // NOTE: This PDF is actually a Life & Savings product (whole life with savings), NOT a CI product.
      // The CI-specific fields below are estimated/placeholder and should be verified.
      "prudential-ci-plan": {
        coverageTerm: "Lifetime",
        premiumTerm: "5/10/15/20/25/30 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 120,
        minorIllnessCount: 40,
        moderateIllnessCount: 20,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20% of sum insured",
        moderateIllnessPayout: "50% of sum insured",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% sum assured + additional death benefit (100% extra first 20 years, decreasing 10%/year after)",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "PRULife Protector II: With-Profits whole life plan. PDF is a Life & Savings product, NOT CI. Premium terms 5/10/15/20/25/30 years. Entry age 1-65 (varies by term). Currency HKD/USD. Guaranteed cash value + reversionary bonus + special bonus. Death benefit 100% SA + additional 100% SA (first 20 years). Accidental death benefit 100% of premiums paid. CI-specific fields above are estimated. Source: prulife-protector-ii-en.pdf",
      },
      // AIA Assemble (自在自選危疾保) - from PDF
      "aia-ci-elite": {
        coverageTerm: "Lifetime",
        premiumTerm: "15/20/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 58,
        minorIllnessCount: 28,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20% of sum insured",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured, max 2,500% total",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "AIA Assemble (自在自選危疾保): Customizable CI coverage. 58 severe diseases, 28 early-stage conditions. Max total payout 2,500% of sum insured. Heart/stroke coverage up to 300%. Source: aia-assemble-ci.pdf",
      },
      // AIA Cancer Care Essence (智護癌症保) - from PDF
      "aia-cancer-care": {
        coverageTerm: "Lifetime",
        premiumTerm: "10/15/20 years",
        entryAgeMin: 18,
        entryAgeMax: 60,
        waitingPeriodDays: 90,
        majorIllnessCount: 80,
        minorIllnessCount: 0,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "N/A",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: false,
        deathBenefit: "100% of sum insured",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "AIA Cancer Care Essence (智護癌症保): Cancer-focused plan covering 80 conditions including TNM staging T1a/T1b/T1c cancers. Entry age 18-60. Multiple cancer claims with 20% early-stage payout. Source: aia-cancer-care.pdf",
      },
      // AIA Executive Care Pro 2 (泰然安心保2) - from PDF
      "aia-executive-care-pro-2": {
        coverageTerm: "Lifetime",
        premiumTerm: "15/18/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 103,
        minorIllnessCount: 53,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20% of sum insured",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "AIA Executive Care Pro 2 (泰然安心保2): 103 conditions (55 severe diseases, 48 early-stage). Entry age 0-65. 100% + 80% payout structure. Source: aia-executive-care-pro-2.pdf",
      },
      // AIA Essence On Your Side (簡緻·愛伴航) - from PDF
      "aia-essence-on-your-side": {
        coverageTerm: "Lifetime",
        premiumTerm: "10/18/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 58,
        minorIllnessCount: 7,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "40% of sum insured",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured, max 280% total",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "AIA Essence On Your Side (簡緻·愛伴航): Participating CI plan covering 58 critical illnesses (57 severe + 1 non-severe), 7 early-stage conditions. Max total payout 280%. AIA Vitality 10% extra coverage. Coverage up to age 85. Source: aia-essence-on-your-side.pdf",
      },
      // AIA On Your Side Insurance Plan 2 (愛伴航2) - from PDF
      "aia-on-your-side-2": {
        coverageTerm: "Lifetime",
        premiumTerm: "10/18/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 58,
        minorIllnessCount: 44,
        moderateIllnessCount: 13,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20% of sum insured",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured, max 1,100% total",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "AIA On Your Side 2 (愛伴航2): Participating CI plan covering 115 diseases (58 severe + 44 early-stage + 13 severe childhood diseases). 10X multiple claims up to 1,000%. Cancer max 600%, heart/stroke max 300%. Continuous cancer cash option (5%/month up to 100 months). Dementia/Parkinson lifetime annuity (6%/year). Extra premium payment option for lower total cost. AIA Vitality 10% extra. Source: aia-on-your-side-2.pdf",
      },
      // AIA Cancer Guardian 3 (癌症全方位保障3) - from PDF
      "aia-cancer-guardian-3": {
        coverageTerm: "Lifetime",
        premiumTerm: "10/15/20 years",
        entryAgeMin: 0,
        entryAgeMax: 75,
        waitingPeriodDays: 90,
        majorIllnessCount: 300,
        minorIllnessCount: 0,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured per claim",
        minorIllnessPayout: "N/A",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: false,
        deathBenefit: "100% of sum insured",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "AIA Cancer Guardian 3 (癌症全方位保障3): Comprehensive cancer protection. 3 rounds of cancer claims, max 900% of sum insured (300% per round). HPV-related benefits. Off-label drug use covered (150% limit per round). 6 rounds of supplementary treatment benefits. Source: aia-cancer-guardian-3.pdf",
      },

      "fwd-crisis-one-master": {
        coverageTerm: "To age 100",
        premiumTerm: "10/15/20/25/30 years",
        entryAgeMin: 1,
        entryAgeMax: 70,
        waitingPeriodDays: 90,
        majorIllnessCount: 68,
        minorIllnessCount: 80,
        moderateIllnessCount: 22,
        majorIllnessPayout: "100% of sum insured + accumulated reversionary bonus + special bonus",
        minorIllnessPayout: "25% of sum insured (severe diseases); 10% (bipolar, MDD, OCD, schizophrenia); 8% (severe eczema/urticaria/angioedema)",
        moderateIllnessPayout: "25% of sum insured (children diseases); 8% (severe eczema/urticaria/angioedema for children)",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured + accumulated bonuses + additional 35% extension death benefit if death within 1 year of first major CI claim",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "FWD Crisis One Master (危疾緻尚保系列): 170 diseases (68 major + 80 severe + 22 children). Max coverage 1300% (cancer group 650% + non-cancer group 650%). Entry age 1-70 (varies: 10yr→1-60, 15yr→1-55, 20yr→1-50, 25/30yr further limits). Non-guaranteed premium. HKD/USD. Alzheimer's/Parkinson's lifetime annuity 6%/year (Enhanced version). Mental health coverage for anxiety & mild depression (up to age 70). ICU 3+ days: 50% SA. Critical medical care: 20% SA. Extra protection 90% (age≤35) or 60% (age>35) within first 15 years. Specified cancer extra 25%. Congenital disease covered (90-day waiting). Experimental drug coverage 20%. Health check every 2 years. Source: fwd-crisis-one-master.pdf",
      },
      "fwd-crisis-u-supporter": {
        coverageTerm: "To age 100",
        premiumTerm: "10/15/20/25/30 years",
        entryAgeMin: 1,
        entryAgeMax: 70,
        waitingPeriodDays: 90,
        majorIllnessCount: 62,
        minorIllnessCount: 65,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured + special bonus",
        minorIllnessPayout: "20% of sum insured per claim (special diseases including early-stage cancer, coronary angioplasty, and children special diseases; cap HKD 400,000/USD 50,000 per claim)",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured + special bonus",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "FWD Crisis U Supporter (危疾應援保): 62 critical illnesses + 65 special diseases (incl. 12 children). Max multiple claims 990% (7 times: 1st-2nd 120%, 3rd-7th 150% each). Entry age 1-70 (varies by term: 10yr→1-60, 15yr→1-55, 20yr→1-50). Non-guaranteed premium. HKD/USD. ICU 20%. 3 major diseases cash benefit: cancer 5%/10% per year up to 5 years, AMI/stroke 1%/month up to 6/12 months. Extra protection 75% (age≤35) or 60% (age>35) within first 15 years. Congenital disease covered (90-day waiting). Experimental drug coverage 20% (Enhanced version). Guaranteed cash value + special bonus. Also available as children's version (童步守護) with pregnancy entry age 19-46 at 22+ weeks. Infertility treatment benefit 10%. Mental health support. Source: fwd-crisis-u-supporter.pdf",
      },
      "fwd-easycover-ci": {
        coverageTerm: "To age 100 (renewable)",
        premiumTerm: "Annual/5/10/20 years renewable to age 100",
        entryAgeMin: 1,
        entryAgeMax: 70,
        waitingPeriodDays: 90,
        majorIllnessCount: 62,
        minorIllnessCount: 65,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "35% of sum insured per claim (special diseases incl. early-stage cancer, coronary angioplasty, children special diseases; cap HKD 400,000/USD 50,000 per claim)",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: false,
        deathBenefit: "100% of existing sum insured",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: false,
        participating: false,
        notes: "FWD EasyCover (好易揀危疾保障): Non-participating renewable CI plan. 62 critical illnesses + 65 special diseases (incl. 12 children). Entry age 1-70. Non-guaranteed renewable premium. HKD/USD. ICU (3+ days with invasive life support): 20% SA. Special disease multiple claims up to 100% SA total. 3 major diseases extra 50% (optional rider). 3 major diseases extra medical coverage (optional, first-in-market): reimbursement up to 100% SA or HKD 1M after threshold. Convertible to limited-pay lifetime CI at age ≤55 without health proof. Premium waiver when total claims reach 100% SA. Health check vouchers at year 2,4,6,8,10. Source: fwd-easycover-ci.pdf",
      },
      "pingan-ruyi-quanneng-ci": {
        coverageTerm: "To age 60/65/70/75/80 (policyholder choice)",
        premiumTerm: "10/15/20 years",
        entryAgeMin: 18,
        entryAgeMax: 54,
        waitingPeriodDays: 90,
        majorIllnessCount: 120,
        minorIllnessCount: 40,
        moderateIllnessCount: 20,
        majorIllnessPayout: "100% of sum insured (1 time only)",
        minorIllnessPayout: "20% of sum insured per claim (up to 5 times, each disease once)",
        moderateIllnessPayout: "50% of sum insured per claim (up to 5 times, each disease once)",
        multipleClaims: true,
        cancerMultipleClaims: false,
        heartStrokeMultipleClaims: false,
        deathBenefit: "100% of sum insured (pre-illness death); Cash value (post-illness death)",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "Ping An Ruyi Quanneng CI 2025 (平安附加如意全能2025提前给付重大疾病保险): CI rider paired with Ruyi Quanneng main endowment. Entry age 18-54. Coverage to age 60/65/70/75/80. 120 major illnesses (1 claim), 20 moderate (50% SA each, max 5), 40 mild (20% SA each, max 5). Waiting period 90 days. Premium waiver included. Cash value. Policy loan up to 80% of CV. Example: 30yo male, 20yr term, to age 70, SA 300K, annual premium ¥5,010. Source: pingan-ruyi-quanneng-2025-ci.pdf",
      },
      "taikang-lexiangjiankang-2026": {
        coverageTerm: "Lifetime",
        premiumTerm: "Single/3/5/10/15/20/25/30 years",
        entryAgeMin: 0,
        entryAgeMax: 70,
        waitingPeriodDays: 90,
        majorIllnessCount: 120,
        minorIllnessCount: 0,
        moderateIllnessCount: 0,
        majorIllnessPayout: "Greater of (SA, total premiums paid, cash value)",
        minorIllnessPayout: "N/A",
        moderateIllnessPayout: "N/A",
        multipleClaims: false,
        cancerMultipleClaims: false,
        heartStrokeMultipleClaims: false,
        deathBenefit: "Greater of (SA, total premiums paid, cash value)",
        premiumWaiver: true,
        earlyStageCoverage: false,
        cashValue: true,
        participating: false,
        notes: "Taikang Lexiang Jiankang 2026 (泰康乐享健康2026重大疾病保险): Standalone whole life CI product. Entry age 0-70. Coverage lifetime. 120 major illnesses (1 claim, then terminates). Also covers full disability and terminal illness stage. Death benefit: greater of (SA, premiums paid, CV). No moderate/mild disease classification. Waiting period 90 days. Example: 30yo male, 20yr term, SA 200K, annual premium ¥7,240. CV exceeds premiums by year 20 (¥104,400 vs ¥144,800 total premiums). Cash value approaches SA over time. Source: taikang-lexiangjiankang-2026.pdf",
      },
      "cpic-jinshengwuyou-kids": {
        coverageTerm: "Lifetime",
        premiumTerm: "Single/5/10/15/20/30 years",
        entryAgeMin: 0,
        entryAgeMax: 17,
        waitingPeriodDays: 180,
        majorIllnessCount: 120,
        minorIllnessCount: 0,
        moderateIllnessCount: 0,
        majorIllnessPayout: "Greater of (SA, cash value) for ages 18+; Total premiums paid for ages <18",
        minorIllnessPayout: "N/A",
        moderateIllnessPayout: "N/A",
        multipleClaims: false,
        cancerMultipleClaims: false,
        heartStrokeMultipleClaims: false,
        deathBenefit: "Under 18: premiums paid; 18+: greater of (SA, CV)",
        premiumWaiver: false,
        earlyStageCoverage: false,
        cashValue: true,
        participating: false,
        notes: "CPIC Jinsheng Wuyou Kids (太保金生无忧2024少儿版重大疾病保险): Children's whole life CI. Entry age 0-17. 120 major illnesses + 20 juvenile-specific CI (extra 100% SA, under 18) + 20 adult-specific CI (extra 100% SA, 18+) + 60 specific diseases (30% SA each, max 3 times). Waiting period 180 days. SA ¥10,000 per unit. Example: 0yo girl, 20yr term, SA 150K, annual premium ¥2,325. CV exceeds premiums by year 19 (¥20,805 vs ¥44,175 total). Source: cpic-jinshengwuyou-kids.pdf",
      },
      "cpic-wenyingjinsheng-ci": {
        coverageTerm: "To age 74/79/84/89 (rider to main annuity plan)",
        premiumTerm: "Single/5/10/15/20 years",
        entryAgeMin: 0,
        entryAgeMax: 53,
        waitingPeriodDays: 180,
        majorIllnessCount: 120,
        minorIllnessCount: 0,
        moderateIllnessCount: 0,
        majorIllnessPayout: "Greater of (SA, CV, total premiums paid) before annuity start; Annuity guaranteed balance after start",
        minorIllnessPayout: "N/A",
        moderateIllnessPayout: "N/A",
        multipleClaims: false,
        cancerMultipleClaims: false,
        heartStrokeMultipleClaims: false,
        deathBenefit: "Under 18: max of (premiums paid, CV); 18+: max of (premiums paid × 150%, CV)",
        premiumWaiver: false,
        earlyStageCoverage: false,
        cashValue: true,
        participating: false,
        notes: "CPIC Wenying Jinsheng CI (太保附加稳赢金生重大疾病保险): Rider CI to main annuity plan. Entry age 0-53. Coverage to age 74/79/84/89. 120 major illnesses. Waiting period 180 days. Death benefit 150% of premiums paid (age 18+). SA ¥10,000 per unit. Example: 30yo male, 10yr term, SA 300K, annual premium ¥3,634.20. Source: cpic-wenyingjinsheng-ci.pdf",
      },
      "manulife-incomeguard-ci": {
        coverageTerm: "To age 100",
        premiumTerm: "10/20/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 365,
        majorIllnessCount: 60,
        minorIllnessCount: 44,
        moderateIllnessCount: 17,
        majorIllnessPayout: "100% of sum insured per claim",
        minorIllnessPayout: "20% of sum insured per claim (early-stage diseases)",
        moderateIllnessPayout: "20% of sum insured per claim (children diseases, up to age 18)",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "110% of total premiums paid minus CI claims paid",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "Manulife IncomeGuard CI (宏健守護危疾入息保障): 121 diseases (60 severe + 44 early-stage + 17 children). Max coverage 1000% SA. Entry age 15 days - 65 (10yr/20yr), 15 days - 60 (25yr). Guaranteed fixed premium. HKD/USD. Min SA HKD 100,000/USD 12,500. 10-year extra benefit: 100% additional for severe CI, 100% additional for early-stage/children. Cancer/AMI/stroke income benefit (annual payments). Premium waiver: full waiver after severe CI; 12-month waiver after early-stage/children claim. 1-year waiting period between claims. TCM cancer treatment reimbursement. Cash value. Source: incomeguard-critical-illness-protector.pdf",
      },
      "manulife-incomeshield-ci": {
        coverageTerm: "To age 100",
        premiumTerm: "10/20/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 365,
        majorIllnessCount: 10,
        minorIllnessCount: 3,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20% of sum insured per claim (early-stage malignant tumors)",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "110% of total premiums paid minus CI claims paid",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "Manulife IncomeShield CI (宏伴護航危疾入息保障): Simplified underwriting CI product. 10 severe CI + 3 early-stage (early malignant tumors). Max cancer/heart/stroke coverage 400% SA. Entry age 15 days - 65 (10yr/20yr), 15 days - 60 (25yr). Guaranteed fixed premium. HKD/USD. Min SA HKD 100,000/USD 12,500. Multiple cancer claims (new,复发, metastasis,持续) + heart/stroke claims. Terminal cancer extra benefit. Inflation protection option. Premium waiver after severe CI claim. 1-year waiting between claims. 3-year waiting for cancer recurrence. Source: incomeshield-critical-illness-protector.pdf",
      },
      "manulife-bright-care-pro": {
        coverageTerm: "To age 100",
        premiumTerm: "10/20/25 years",
        entryAgeMin: 0,
        entryAgeMax: 65,
        waitingPeriodDays: 365,
        majorIllnessCount: 60,
        minorIllnessCount: 44,
        moderateIllnessCount: 19,
        majorIllnessPayout: "100% of sum insured + 50% extra in first 10 years",
        minorIllnessPayout: "20% of sum insured per claim (early-stage diseases, up to 80% total)",
        moderateIllnessPayout: "20% of sum insured per claim (children diseases incl. autism, ADHD, Tourette syndrome, up to age 18)",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "110% of total premiums paid minus CI claims paid",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: false,
        notes: "Manulife Bright Care PRO (活耀人生危疾保PRO): 123 diseases (60 severe + 44 early-stage + 19 children incl. autism, ADHD, Tourette). Entry age 15 days - 65 (10yr/20yr), 15 days - 60 (25yr). Guaranteed fixed premium. HKD/USD. Cancer multiple claims up to 500% SA (1st + 4 additional). Heart/stroke 2 additional claims. ICU Level 1 (3+ days): 20% SA. ICU Level 2 (5+ days + invasive support + complex surgery): 100% SA. Terminal cancer overseas/non-traditional treatment support. Premium waiver after severe CI or Level 2 ICU claim. Parent compassionate premium waiver. 1-year waiting between claims, 3-year for cancer recurrence. Source: manulife-bright-care-pro.pdf",
      },
      // Prudential Guardian CI Series (誠保一生危疾保) - from PDF
      "pru-guardian-ci-series": {
        coverageTerm: "Lifetime (extended coverage to age 86)",
        premiumTerm: "5/10/15/20/25 years",
        entryAgeMin: 1,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 56,
        minorIllnessCount: 49,
        moderateIllnessCount: 22,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20-25% of sum insured",
        moderateIllnessPayout: "5-20% of sum insured (children conditions)",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured + life extension after severe claim",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "Prudential Guardian CI Series (誠保一生危疾保): 127 conditions (56 severe + 49 early-stage + 15 severe children + 7 sub-severe children). Multiple claims up to 1000% (cancer 200%, heart/stroke 200%, dementia 100%, organ 200%, other 200%). Dementia/Parkinson lifetime annuity 6%/year until death. Life extension 100% after severe claim (1 year waiting). Upgrade benefit 50% (first 10 years). 22 children diseases until age 18. Shareholder-backed participating plan. Source: pru-guardian-ci-series.pdf",
      },
      // Prudential CI Extended Care III (危疾加護保III) - from PDF
      "pru-ci-extended-care-iii": {
        coverageTerm: "Lifetime (extended coverage to age 86)",
        premiumTerm: "10/15/20/25 years",
        entryAgeMin: 1,
        entryAgeMax: 65,
        waitingPeriodDays: 90,
        majorIllnessCount: 56,
        minorIllnessCount: 61,
        moderateIllnessCount: 0,
        majorIllnessPayout: "100% of sum insured",
        minorIllnessPayout: "20-25% of sum insured",
        moderateIllnessPayout: "N/A",
        multipleClaims: true,
        cancerMultipleClaims: true,
        heartStrokeMultipleClaims: true,
        deathBenefit: "100% of sum insured",
        premiumWaiver: true,
        earlyStageCoverage: true,
        cashValue: true,
        participating: true,
        notes: "Prudential CI Extended Care III (危疾加護保III): 117 conditions (56 severe + 61 early-stage). Multiple claims up to 860% (cancer 2x100% + cancer treatment extra 2x60%, heart/stroke 2x100%). ICU benefit 20% (3+ days). Upgrade benefit 50% (first 10 years). Family premium waiver for children 1-18. Shareholder-backed participating plan. Source: pru-ci-extended-care-iii.pdf",
      },
    };

    const d = ciDetails[product.slug] || {
      coverageTerm: "Lifetime",
      premiumTerm: "20 years",
      entryAgeMin: 0,
      entryAgeMax: 65,
      waitingPeriodDays: 90,
      majorIllnessCount: 120,
      minorIllnessCount: 40,
      moderateIllnessCount: 20,
      majorIllnessPayout: "100% of sum insured",
      minorIllnessPayout: "20% of sum insured",
      moderateIllnessPayout: "50% of sum insured",
      multipleClaims: true,
      cancerMultipleClaims: true,
      heartStrokeMultipleClaims: true,
      deathBenefit: "100% of sum insured",
      premiumWaiver: true,
      earlyStageCoverage: true,
      cashValue: true,
      participating: false,
      notes: "Data to be verified against official brochures.",
    };

    await prisma.criticalIllnessDetail.create({
      data: {
        productId: product.id,
        ...d,
      },
    });
  }

  for (const product of savingsProducts) {
    // Product-specific details from official brochures
    const details: Record<string, any> = {
      // AIA FlexiAchiever (活享儲蓄計劃) - from PDF
      "aia-savings-leader": {
        premiumTerm: "5/6/15 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 4.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 8,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "AIA FlexiAchiever Savings Plan (活享儲蓄計劃): Participating savings plan. Premium terms: 5/6/15 years. Coverage to age 85. Non-guaranteed terminal bonus (not reversionary). Guaranteed cash value. Example: 40yo male, 5-year term, $550K SA + $250K additional premium shows IRR 7.30% at year 10. Source: aia-savings-leader.pdf",
      },
      // Prudential Enlight Savings - from PDF
      "prudential-enlit-savings": {
        premiumTerm: "5 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 4.0,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 18,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Prudential Enlight Savings (啟耀未來儲蓄): Shareholder-backed participating plan. 5-year premium, whole life coverage. Guaranteed cash coupon 105% of notional amount on 18th policy anniversary. Terminal Bonus only (no reversionary bonus). FlexIncome Option from 18th policy anniversary. Academic Success Award for top exam scores. First-in-market pregnancy coverage from 20th week (Baby version). Policy loan up to 80% of guaranteed cash value. Source: enlit-product-brochure-en.pdf",
      },
      // Prudential Evergreen Growth Saver Plus II - from PDF
      "prudential-evergreen-growth": {
        premiumTerm: "Single/5/8/12 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Reversionary + Terminal",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 4.2,
        guaranteedIrr: 0.8,
        illustratedBreakEvenYear: 9,
        guaranteedBreakEvenYear: 16,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Evergreen Growth Saver Plus II (雋陞儲蓄II): With-Profits Plan. Single/5/8/12 year premium terms. Whole life coverage. Reversionary + Special bonus. Death benefit 100% of premiums paid +3.5%/year up to 135%. Change life assured after 1st year. Academic Success Award (HKDSE 5*, IELTS 8, TOEFL 110, top 10 universities HKD 20,000). No medical info required. Policy loan up to 80%. Source: evergreen-growth-saver-plus-ii-en.pdf",
      },
      // Prudential Prime Ace - from PDF
      "prudential-prime-ace": {
        premiumTerm: "3 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 1,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Reversionary + Terminal",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 4.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 7,
        guaranteedBreakEvenYear: 15,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Prime Ace Insurance Plan: With-Profits Plan, 3-year premium only, entry age 1-80, USD only (min notional USD 600,000). Reversionary + Special bonus. FlexIncome Option from 5th anniversary. Wealth-Split Option. Unlimited change of life assured. Succeeding owner/contingent life assured options. Limited offer. Source: pace-product-brochure-en.pdf",
      },
      // Prudential Prime Eternity - from PDF
      "prudential-prime-eternity": {
        premiumTerm: "Single premium",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Dividend",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 5.2,
        guaranteedIrr: 0.03,
        illustratedBreakEvenYear: 10,
        guaranteedBreakEvenYear: 10,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Prime Eternity (世譽財富): Shareholder-backed participating plan, single premium. Guaranteed cash value = 85% of premium at start. Terminal Dividend only (no reversionary). Dividend Lock-in Option from 10th anniversary. Policy loan up to 80% of guaranteed cash value. Example: 40yo male, USD 1M single premium: illustrated IRR 5.20% at yr 10, 6.38% at yr 20, 6.50% at yr 45; guaranteed IRR 0.03% at yr 10. ~16x return at year 45 (non-guaranteed). Wealth-Split Option. FlexLegacy death benefit settlement. Source: prime-eternity-en.pdf",
      },
      // FWD Evergreen Savings - from PDF (AeconoLife20)
      "fwd-evergreen-savings": {
        premiumTerm: "5 years",
        coverageTerm: "20 years",
        entryAgeMin: 0,
        entryAgeMax: 70,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.8,
        guaranteedIrr: 2.0,
        illustratedBreakEvenYear: 12,
        guaranteedBreakEvenYear: 15,
        policyLoan: true,
        changePolicyholder: false,
        changeInsured: false,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: false,
        notes: "FWD AeconoLife20: Non-participating endowment plan. Data estimated from product type.",
      },
      // FWD Noble Fortune (寰薈致富) - from PDF
      "fwd-noble-fortune": {
        premiumTerm: "Flexible (subject to minimum required premium)",
        coverageTerm: "To age 100",
        entryAgeMin: 5,
        entryAgeMax: 70,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.5,
        guaranteedIrr: 2.3,
        illustratedBreakEvenYear: 8,
        guaranteedBreakEvenYear: 10,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: false,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "FWD Noble Fortune (寰薈致富): Universal life with savings element. Entry age 5-70. USD only. Min sum insured USD 500,000. Guaranteed minimum crediting interest rate 2.30% p.a. for whole benefit term. Extra 0.20% p.a. in first 2 policy years if crediting rate exceeds guaranteed minimum. Flexible premium (subject to minimum required premium and maximum). Premium charge 6% of each payment. Free partial surrender 10% of Account Value per year. Death benefit: higher of Account Value or (Sum Insured less free partial surrenders). No reversionary/terminal bonus (universal life crediting interest structure). Source: fwd-noble-fortune.pdf",
      },
      // FWD MaxFocus Legacy II (盈聚天下II) - from PDF
      "fwd-maxfocus-legacy-ii": {
        premiumTerm: "Single/2/3/5/10 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Reversionary + Terminal",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 6.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 6,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "FWD MaxFocus Legacy II (盈聚天下II): Participating savings plan. Entry age 1(15 days)-80 (single/2yr), 1-75 (3/5yr), 1-70 (10yr). 8 currencies: HKD, USD, RMB, GBP, CAD, AUD, SGD, EUR. Guaranteed cash value + reversionary bonus + special bonus. Illustrated IRR up to 6.5% p.a. at year 25 (non-guaranteed). Min nominal amount varies by term/currency (e.g. USD 2,000 for 10yr). Death benefit: higher of 100% premiums paid or (guaranteed CV + reversionary bonus face value + special bonus face value + bonus lock-in balance). Policy split from year 3. Bonus lock-in option. Premium holiday (2yr for 5yr term, 4yr for 10yr term). Newborn baby award HKD 20,000. Educational awards. Life milestone awards HKD 3,000 each. FlexLegacy death benefit settlement (5 options). Change policyholder & insured. Source: fwd-maxfocus-legacy-ii.pdf",
      },
      "fwd-wealthicon-supreme-iii": {
        premiumTerm: "Single premium",
        coverageTerm: "To age 138 of latest insured",
        entryAgeMin: 0,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Annual Bonus + Special Bonus",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 5.0,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 6,
        guaranteedBreakEvenYear: 15,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "FWD WealthICON Supreme III (智盈匯聚優越版III): Participating savings plan. Single premium. Entry age 1(15 days)-80. Coverage to age 138 of latest insured. HKD/USD/RMB. Min premium HKD 100,000/USD 12,500/RMB 80,000. Guaranteed cash value + annual bonus (non-guaranteed, from year 3) + special bonus (non-guaranteed, from year 3). Annual bonus: cash or accumulate with interest. Special bonus lock-in option from year 15 (convert to annual bonus). Death benefit: higher of (guaranteed CV + special bonus) or 105% premiums paid + accumulated annual bonus. Change policyholder & insured. Policy split. Source: fwd-wealthicon-supreme-iii.pdf",
      },
      "fwd-wealthicon-horizon": {
        premiumTerm: "Single premium",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Reversionary + Terminal",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 5.0,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 4,
        guaranteedBreakEvenYear: 15,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "FWD WealthICON Horizon (智盈超凡): Participating savings plan. Single premium only. Entry age 1(15 days)-80. Lifetime coverage. HKD/USD. Min premium HKD 400,000/USD 50,000. Guaranteed cash value + reversionary bonus + special bonus. Expected breakeven at year 4 (non-guaranteed). Example: USD 300K single premium, 40yo male → year 10 value USD 495,598 (~1.7x), year 25 value ~4.3x. Death benefit: higher of 100% premiums paid or (guaranteed CV + bonuses + lock-in balance). Policy split from year 3. Bonus lock-in. FlexLegacy death benefit settlement (5 options). Change policyholder & insured. Accidental death benefit 200% of premiums (first 10 years). Source: fwd-wealthicon-horizon.pdf",
      },
      // AIA GlobalFlexi Savings (環宇盈活儲蓄) - from PDF
      "aia-globalflexi-savings": {
        premiumTerm: "5 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 4.56,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 8,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "AIA GlobalFlexi Savings (環宇盈活儲蓄): Multi-currency participating savings plan supporting 9 currencies (HKD, USD, GBP, EUR, SGD, AUD, RMB, MOP, CAD). Premium term 5 years. Coverage to age 85. Education benefits (HKDSE 5*, IELTS 8, etc.). AIA Vitality extra coverage. 180-day waiting period. Illustrated IRR 4.56% at year 29. Source: aia-globalflexi-savings.pdf",
      },
      // AIA Wealth Flexi Savings (財富盈活儲蓄) - from PDF
      "aia-wealth-flexi-savings": {
        premiumTerm: "5 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 4.79,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 8,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "AIA Wealth Flexi Savings (財富盈活儲蓄): Multi-currency participating savings plan supporting 9 currencies (HKD, USD, GBP, EUR, SGD, AUD, RMB, MOP, CAD). Premium term 5 years. Coverage to age 85. Education benefits. AIA Vitality extra coverage. 180-day waiting period. Change policyholder feature included. Illustrated IRR 4.79% at year 30. Source: aia-wealth-flexi-savings.pdf",
      },

      // Ping An Ruyi Quanneng Endowment - from PDF
      "pingan-ruyi-quanneng-main": {
        premiumTerm: "10/15/20 years",
        coverageTerm: "To age 60/65/70/75/80",
        entryAgeMin: 18,
        entryAgeMax: 54,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 0,
        guaranteedIrr: 0,
        illustratedBreakEvenYear: 20,
        guaranteedBreakEvenYear: 20,
        policyLoan: true,
        changePolicyholder: false,
        changeInsured: false,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: false,
        notes: "Ping An Ruyi Quanneng 2025 Endowment (平安平安如意全能2025两全保险): Endowment main plan paired with CI rider. Entry age 18-54. Coverage to age 60/65/70/75/80. Maturity benefit: greater of (total premiums paid) or basic SA. Death benefit: greater of (premiums × years) or SA. Policy loan up to 80% of CV. Example: 30yo male, 20yr term, to age 70, SA 300K, annual premium ¥8,220. Year 20 CV ¥129,180. Maturity (year 40) benefit ¥300,000. Source: pingan-ruyi-quanneng-2025-main.pdf",
      },
      // Ping An Shengshi Jinyue Premium - from PDF
      "ping-an-shengshi-jinyue-premium": {
        premiumTerm: "Single/3/5/10/15/20 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.7,
        guaranteedIrr: 2.7,
        illustratedBreakEvenYear: 20,
        guaranteedBreakEvenYear: 20,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Ping An Shengshi Jinyue Premium (平安盛世金越尊享版终身寿险): Non-participating whole life with guaranteed 3.5% annual SA increase. Entry age 0-75 (born 28+ days). Dual insured design (e.g. parent + child to extend growth cycle). Death benefit: max of (SA × 1.035^(n-1), 160%/140%/120% of premiums paid by age). Policy loan up to 80% of CV. Example: 40yo male, 10yr term, annual premium ¥50,000, SA ¥381,098. Year 20 CV ¥745,998 (1.49× premiums), Year 30 CV ¥1,052,287 (2.10×), Year 40 CV ¥1,484,299 (2.97×). Source: pingan-shengshi-jinyue-zunxiang.pdf",
      },
      "taikang-zunxiang-shijia-zeng-e": {
        premiumTerm: "Single/3/6/10/15/20 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 73,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.2,
        guaranteedIrr: 2.2,
        illustratedBreakEvenYear: 7,
        guaranteedBreakEvenYear: 7,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Taikang Zunxiang Shijia Increasing Edition (泰康尊享世家增额版2024终身寿险): Non-participating whole life with guaranteed 2.75% annual effective SA increase. Entry age 0-73 (born 30+ days). Dual insured design. Death/full disability benefit: max of (effective SA, CV, premiums × 160%/140%/120% by age). Transport accident extra benefit = basic SA. Premium waiver for dual insured. Waiting period 90 days. Policy loan up to 80% of CV. Example: 30yo male, 6yr term, ¥50,000/yr, SA ¥261,165. Year 7 CV ¥312,875 (exceeds ¥300,000 premiums). Year 20 CV ¥443,675. Source: taikang-zunxiang-shijia-zeng-e.pdf",
      },
      "taikang-zunxiang-shijia-flagship": {
        premiumTerm: "Single/3/6/10/15/20 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 70,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.4,
        guaranteedIrr: 2.4,
        illustratedBreakEvenYear: 7,
        guaranteedBreakEvenYear: 7,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Taikang Zunxiang Shijia Flagship Edition (泰康尊享世家旗舰版终身寿险): Non-participating whole life with guaranteed 3.0% annual effective SA increase (higher than zeng-e's 2.75%). Entry age 0-70 (born 30+ days). Dual insured design. Death/full disability benefit: max of (effective SA, CV, premiums × 160%/140%/120% by age). Premium waiver for dual insured. Waiting period 90 days. Policy loan up to 80% of CV. Example: 30yo male, 6yr term, ¥50,000/yr, SA ¥258,285. Year 7 CV ¥313,970 (exceeds ¥300,000 premiums). Year 20 CV ¥459,930 (1.53× premiums). Year 30 CV ¥618,105 (2.06×). Source: taikang-zunxiang-shijia-flagship.pdf",
      },
      "cpic-xiangbanzhizun-2024s": {
        premiumTerm: "Single/3/5/6/10 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 70,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Cash dividend (accumulated interest or paid-up addition)",
        terminalBonus: false,
        reversionaryBonus: true,
        illustratedIrr: 2.5,
        guaranteedIrr: 1.5,
        illustratedBreakEvenYear: 9,
        guaranteedBreakEvenYear: 9,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "CPIC Xiangban Zhizun 2024S (太保长相伴至尊2024S终身寿险分红型): Participating whole life with guaranteed 2.0% annual effective SA increase. Entry age 0-70 (female 0-70, male 0-68, born 5+ days). Dual insured design with accidental death/full disability premium waiver. Cash dividend (2 options: accumulate with 2.0% interest or buy paid-up additions). Waiting period 90 days. Policy loan. Annual red reduction up to 20%. Example: 0yo boy, 6yr term, ¥100,000/yr, SA ¥520,490. Year 9 CV ¥616,550 (exceeds ¥600,000 premiums). Year 20 guaranteed CV ¥766,460 + accum. dividend ¥137,777 = ¥904,237. Year 30 guaranteed CV ¥933,790 + accum. dividend ¥264,110 = ¥1,197,900. Source: cpic-xiangbanzhizun-2024s.pdf",
      },
      // Taikang Zengduoduo - from PDF
      "taikang-zengduoduo": {
        premiumTerm: "Single/Lump sum",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 70,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 2.5,
        guaranteedIrr: 2.5,
        illustratedBreakEvenYear: 5,
        guaranteedBreakEvenYear: 5,
        policyLoan: true,
        changePolicyholder: false,
        changeInsured: false,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "泰康放心理财财富版终身寿险（万能型）: Universal life with 2.5% minimum guaranteed rate. Source: taikang-fangxin-caifu.pdf",
      },
      // CPIC Evergreen Whole Life - from PDF
      "cpic-evergreen-whole-life": {
        premiumTerm: "3 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: false,
        guaranteedCashValue: true,
        nonGuaranteedBonus: false,
        dividendType: undefined,
        terminalBonus: false,
        reversionaryBonus: false,
        illustratedIrr: 3.0,
        guaranteedIrr: 2.5,
        illustratedBreakEvenYear: 7,
        guaranteedBreakEvenYear: 9,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: false,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "太保鑫相伴（至尊版）终身寿险: Entry age 0-75. Source: cpic-xin-xiang-ban.pdf",
      },
      "manulife-genesis-centurion": {
        premiumTerm: "Single/3/5 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 6.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 6,
        guaranteedBreakEvenYear: 27,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Manulife Genesis Centurion (宏摯家傳承): Participating savings plan. Entry age 0-80 (single), 0-75 (3yr/5yr). Lifetime coverage. 7 currencies: USD, HKD, CNY, CAD, AUD, GBP, SGD. Guaranteed cash value + terminal bonus only (no reversionary bonus). Illustrated IRR 6.5%+ at year 27 (non-guaranteed). Guaranteed IRR 0.50%. Expected breakeven year 6 (non-guaranteed). Fixed guaranteed premium. Currency conversion from year 3. Premium holiday (5yr term only, max 2 years). Policy split from year 5. Terminal bonus lock-in from year 10 (max 50% in any 25 consecutive years). Worry-free option for non-guaranteed income from terminal bonus. Body & mind protection (CI + mental health): lock up to 100% terminal bonus. Death benefit: higher of guaranteed CV or total premiums paid + terminal bonus. Accidental death extra 100% (first 5 years). Source: genesis-centurion.pdf",
      },
      "manulife-prestige-achiever": {
        premiumTerm: "Single premium",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 80,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Terminal Bonus",
        terminalBonus: true,
        reversionaryBonus: false,
        illustratedIrr: 6.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 5,
        guaranteedBreakEvenYear: 20,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: false,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Manulife Prestige Achiever (財摯宏耀): Participating savings plan. Single premium only. Entry age 0-80. Lifetime coverage. USD only. Min premium USD 6,000. Guaranteed cash value up to 83% of premiums paid from day 1 + terminal bonus only (no reversionary bonus). Illustrated IRR capped at 6.5% (non-guaranteed, non-HKD). Terminal bonus lock-in from year 10 (max 50% in 25 consecutive years). Worry-free option for non-guaranteed income. Body & mind protection (CI + mental health). Policy split from year 5. Change insured from year 1. Change policyholder. Accidental death extra 100% premiums (first 5 years). Death benefit: higher of guaranteed CV or total premiums paid + terminal bonus + accumulated income. Source: prestige-achiever.pdf",
      },
      // Prudential Entrust Multi-Currency (信守明天多元貨幣計劃) - from PDF
      "pru-entrust-multi-currency": {
        premiumTerm: "5 years",
        coverageTerm: "Lifetime",
        entryAgeMin: 0,
        entryAgeMax: 75,
        participating: true,
        guaranteedCashValue: true,
        nonGuaranteedBonus: true,
        dividendType: "Reversionary + Terminal",
        terminalBonus: true,
        reversionaryBonus: true,
        illustratedIrr: 4.5,
        guaranteedIrr: 0.5,
        illustratedBreakEvenYear: 8,
        guaranteedBreakEvenYear: 18,
        policyLoan: true,
        changePolicyholder: true,
        changeInsured: true,
        educationPlanning: true,
        retirementPlanning: true,
        legacyPlanning: true,
        notes: "Prudential Entrust Multi-Currency (信守明天多元貨幣計劃): Shareholder-backed participating plan with annual (reversionary) + one-off (terminal) bonuses. Multi-currency support (HKD, USD, CNY, GBP, EUR, CAD, AUD). FlexIncome Option available. SEN benefit. Policy loan up to 80%. Source: pru-entrust-multi-currency.pdf",
      },
    };

    const d = details[product.slug] || {
      premiumTerm: "5 years",
      coverageTerm: "Lifetime",
      entryAgeMin: 0,
      entryAgeMax: 75,
      participating: product.region === "Hong Kong",
      guaranteedCashValue: true,
      nonGuaranteedBonus: product.region === "Hong Kong",
      dividendType: product.region === "Hong Kong" ? "Reversionary + Terminal" : undefined,
      terminalBonus: product.region === "Hong Kong",
      reversionaryBonus: product.region === "Hong Kong",
      illustratedIrr: product.region === "Hong Kong" ? 4.5 : 3.0,
      guaranteedIrr: product.region === "Hong Kong" ? 1.0 : 2.5,
      illustratedBreakEvenYear: product.region === "Hong Kong" ? 8 : 6,
      guaranteedBreakEvenYear: product.region === "Hong Kong" ? 15 : 8,
      policyLoan: true,
      changePolicyholder: true,
      changeInsured: product.region === "Hong Kong",
      educationPlanning: true,
      retirementPlanning: true,
      legacyPlanning: true,
      notes: "Data to be verified against official brochures.",
    };

    await prisma.savingsDetail.create({
      data: {
        productId: product.id,
        ...d,
        currency: product.currency,
        supportedCurrencies: JSON.stringify(product.supportedCurrencies ?? []),
      },
    });
  }

  console.log("Created product details");

  // ==================== GLOSSARY TERMS ====================
  const glossaryTerms = [
    { term: "IRR", slug: "irr", definition: "Internal Rate of Return (IRR) is a metric used to estimate the annualized return of an insurance product over a specific period, taking into account the timing and amount of cash flows.", category: "Financial" },
    { term: "Guaranteed Cash Value", slug: "guaranteed-cash-value", definition: "The minimum cash value that the insurance company guarantees to pay if the policy is surrendered. This amount is specified in the policy contract.", category: "Policy Value" },
    { term: "Non-guaranteed Bonus", slug: "non-guaranteed-bonus", definition: "Additional returns that may be paid by the insurance company based on the performance of its investment portfolio. These are not guaranteed and may vary.", category: "Policy Value" },
    { term: "Surrender Value", slug: "surrender-value", definition: "The amount paid to the policyholder when a life insurance policy is cancelled before it matures or before the insured event occurs.", category: "Policy Value" },
    { term: "Participating Policy", slug: "participating-policy", definition: "A life insurance policy that participates in the profits of the insurance company, typically through dividends or bonuses.", category: "Policy Type" },
    { term: "Whole Life Insurance", slug: "whole-life-insurance", definition: "A type of life insurance that provides coverage for the entire lifetime of the insured, as long as premiums are paid.", category: "Policy Type" },
    { term: "Critical Illness Insurance", slug: "critical-illness-insurance", definition: "A type of insurance that pays a lump sum benefit upon diagnosis of a specified critical illness or medical condition.", category: "Insurance Type" },
    { term: "Savings Insurance", slug: "savings-insurance", definition: "A type of life insurance product that combines insurance protection with savings or investment features.", category: "Insurance Type" },
    { term: "Annuity", slug: "annuity", definition: "A financial product that pays out a fixed stream of income to an individual, typically used as an income stream for retirees.", category: "Insurance Type" },
    { term: "Premium Term", slug: "premium-term", definition: "The period during which the policyholder is required to pay premiums for the insurance policy.", category: "Policy Terms" },
    { term: "Coverage Term", slug: "coverage-term", definition: "The period during which the insurance policy provides coverage or protection.", category: "Policy Terms" },
    { term: "Policy Loan", slug: "policy-loan", definition: "A loan that a policyholder can take against the cash value of their life insurance policy.", category: "Policy Features" },
    { term: "Break-even Year", slug: "break-even-year", definition: "The year in which the total cash value of a policy equals the total premiums paid, meaning the policyholder has recovered their investment.", category: "Financial" },
    { term: "Dividend", slug: "dividend", definition: "A portion of the insurance company's profits distributed to policyholders of participating policies.", category: "Policy Value" },
    { term: "Terminal Bonus", slug: "terminal-bonus", definition: "A one-time bonus paid when a policy matures, is surrendered, or upon the death of the insured. It is typically non-guaranteed.", category: "Policy Value" },
    { term: "Reversionary Bonus", slug: "reversionary-bonus", definition: "A bonus declared annually by the insurance company that is added to the guaranteed sum assured of a participating policy.", category: "Policy Value" },
    { term: "Multi-Currency Policy", slug: "multi-currency-policy", definition: "An insurance policy that allows the policyholder to choose from multiple currencies for premium payment and benefit payout.", category: "Policy Features" },
    { term: "Legacy Planning", slug: "legacy-planning", definition: "The process of organizing and managing assets to be passed on to beneficiaries, often using insurance products as tools for wealth transfer.", category: "Planning" },
    { term: "Retirement Planning", slug: "retirement-planning", definition: "The process of determining retirement income goals and the actions necessary to achieve those goals, often involving insurance and investment products.", category: "Planning" },
    { term: "Education Planning", slug: "education-planning", definition: "The process of saving and investing for future education expenses, sometimes using insurance products with savings features.", category: "Planning" },
    { term: "Cancer Multiple Claims", slug: "cancer-multiple-claims", definition: "A feature in critical illness insurance that allows multiple claims for cancer-related conditions, subject to specified conditions and waiting periods.", category: "Policy Features" },
    { term: "Premium Waiver", slug: "premium-waiver", definition: "A benefit that waives future premium payments if the policyholder becomes totally disabled or is diagnosed with a specified condition.", category: "Policy Features" },
  ];

  for (const term of glossaryTerms) {
    await prisma.glossaryTerm.create({ data: term });
  }

  console.log(`Created ${glossaryTerms.length} glossary terms`);

  // ==================== COMPARISONS ====================
  // Generate comparisons for same-category products
  const comparisons = [];
  
  // HK CI comparisons
  for (let i = 0; i < ciProducts.length; i++) {
    for (let j = i + 1; j < ciProducts.length; j++) {
      const a = ciProducts[i];
      const b = ciProducts[j];
      const slug = `${a.slug}-vs-${b.slug}`;
      const comparison = await prisma.comparison.create({
        data: {
          productAId: a.id,
          productBId: b.id,
          slug,
          basicSummary: `Compare ${a.displayName} and ${b.displayName} across coverage, features, and benefits.`,
        },
      });
      comparisons.push(comparison);
    }
  }

  // Savings comparisons (HK vs HK, Mainland vs Mainland)
  const hkSavings = savingsProducts.filter((p) => p.region === "Hong Kong");
  const mainlandSavings = savingsProducts.filter((p) => p.region === "Mainland China");

  for (const group of [hkSavings, mainlandSavings]) {
    for (let i = 0; i < group.length; i++) {
      for (let j = i + 1; j < group.length; j++) {
        const a = group[i];
        const b = group[j];
        const slug = `${a.slug}-vs-${b.slug}`;
        const comparison = await prisma.comparison.create({
          data: {
            productAId: a.id,
            productBId: b.id,
            slug,
            basicSummary: `Compare ${a.displayName} and ${b.displayName} across returns, features, and benefits.`,
          },
        });
        comparisons.push(comparison);
      }
    }
  }

  console.log(`Created ${comparisons.length} comparisons`);

  console.log("Seed completed successfully!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
